[build]
  dockerfile = "./Dockerfile"

[env]
  FLY_APP_NAME = "crypto-bot-3-white-wind-424"
  REDIS_URL = "redis://default:3fb87281db1b4ca38a98efad70b37e8e@fly-crypto-bot-redis.upstash.io:6379"
  TELEGRAM_BOT_TOKEN = "7874445351:AAFfzBb9heQAEkK7-FuuAdpPMokWNG-FNVY"
  PORT = "8080"

app = "crypto-bot-3-white-wind-424"
primary_region = "jnb"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"
    restart_limit = 0

[experimental]
  auto_rollback = true

[processes]
  app = "gunicorn main:app --bind 0.0.0.0:8080"
  worker = "celery -A celery_worker worker --loglevel=info"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
