app = "crypto-bot-3-white-wind-424"
primary_region = "jnb"

[build]
  dockerfile = "./Dockerfile"

[env]
  FLY_APP_NAME = "crypto-bot-3-white-wind-424"
  REDIS_URL = "redis://default:3fb87281db1b4ca38a98efad70b37e8e@fly-crypto-bot-redis.upstash.io:6379"

[http_service]
  internal_port = 8080
  force_https = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[experimental]
  auto_rollback = true

 [processes]
  app = "python main.py"
  worker = "celery -A celery_worker.py --loglevel=info"
