from .start import start
from .help import help_command
from .balance import balance_command
from .trade import trade_command
from .autobot import autobot_command
from .autobot_config import autobot_config_command
from .leaderboard import leaderboard_command
from .register import register_command
from .setplatform import setplatform_command
from .setstrategy import setstrategy_command
from .setamount import setamount_command
from .setbase import setbase_command
from .showconfig import showconfig_command
